import com.espertech.esper.common.client.EPCompiled;
import com.espertech.esper.common.client.EventBean;
import com.espertech.esper.common.client.EventType;
import com.espertech.esper.common.client.configuration.Configuration;
import com.espertech.esper.common.client.json.minimaljson.Json;
import com.espertech.esper.common.client.json.minimaljson.JsonArray;
import com.espertech.esper.common.client.json.minimaljson.JsonNumber;
import com.espertech.esper.common.client.json.minimaljson.JsonObject;
import com.espertech.esper.common.client.json.minimaljson.JsonValue;
import com.espertech.esper.common.internal.support.SupportBean;
import com.espertech.esper.common.internal.support.SupportBean_S0;
import com.espertech.esper.common.internal.support.SupportBean_S1;
import com.espertech.esper.common.internal.support.SupportBean_S2;
import com.espertech.esper.compiler.client.CompilerArguments;
import com.espertech.esper.compiler.client.EPCompilerProvider;
import com.espertech.esper.runtime.client.DeploymentOptions;
import com.espertech.esper.runtime.client.EPDeployment;
import com.espertech.esper.runtime.client.EPRuntime;
import com.espertech.esper.runtime.client.EPRuntimeProvider;
import com.espertech.esper.runtime.client.EPStatement;
import com.espertech.esper.runtime.client.UpdateListener;
import com.espertech.esper.runtime.internal.kernel.service.EPRuntimeSPI;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * Direct Esper 9.0.0 oracle for the Draft 4.446 'epl-other-plan-in-keyword'
 * unit: EPLOtherPlanInKeywordQuery ordinals 0-8.  Each scenario case replays
 * inside its own runtime; there is no virtual time, no SODA phase and no
 * invalid-compile probe.  Every observed statement carries the suite's
 * byte-exact INDEX_CALLBACK_HOOK @Hook(INTERNAL_QUERY_PLAN) annotation; the
 * hook resolves to a compile-time no-op mirror of
 * com.espertech.esper.regressionlib.support.util.SupportQueryPlanIndexHook
 * generated by the runner script because regression-lib is not on the oracle
 * classpath (the suite's plan-shape assertions are harness-internal and emit
 * no records, so deploy-only cases acknowledge each deployment with a
 * "deployed" record instead).
 *
 * Ordinal 0 (EPLOtherNotIn) deploys the unidirectional not-in join once; the
 * suite asserts only the query-plan shape, so the case emits a single
 * "deployed" record and sends no events.
 *
 * Ordinal 1 (EPLOtherMultiIdxMultipleInAndMultirow) replays the suite's
 * tryAssertionMultiIdx send script against three surfaces: the unidirectional
 * join (multi-idx-join), the keepall named window S1Window fed by an insert
 * and probed by an on-SupportBean_S0 trigger (multi-idx-window), and the
 * primary-key table S1Table with explicit indexes S1Idx1-4 probed by the same
 * trigger (multi-idx-table).  A row matches when (p00 = p10 OR p00 = p11)
 * AND (p01 = p12 OR p01 = p13); joined rows carry the s0/s1 fragments.
 *
 * Ordinal 2 (EPLOtherMultiIdxSubquery) selects s0.id as c0 plus the
 * selectFrom collection of matching s1.id as c1 (null when nothing matches)
 * over SupportBean_S0, then deploys the coercion-absence probe
 * 'select *,(select * from SupportBean_S0#keepall as s0 where
 * sb.longPrimitive in (id)) from SupportBean as sb' as a deploy-only step.
 *
 * Ordinal 3 (EPLOtherSingleIdxMultipleInAndMultirow) replays
 * tryAssertionSingleIdx against the mirrored three surfaces: the
 * unidirectional join with the keepall on S0 (single-idx-join), the keepall
 * named window S0Window probed by an on-SupportBean_S1 trigger
 * (single-idx-window), and the primary-key table S0Table with indexes
 * S0Idx1-2 (single-idx-table).
 *
 * Ordinal 4 (EPLOtherSingleIdxSubquery) mirrors ordinal 2 with s1.id as c0
 * and the selectFrom collection of matching s0.id as c1, then deploys the
 * coercion-absence probe 'select *,(select * from SupportBean#keepall as sb
 * where sb.longPrimitive in (s0.id)) from SupportBean_S0 as s0'.
 *
 * Ordinals 5 and 6 (EPLOtherSingleIdxConstants / EPLOtherMultiIdxConstants)
 * join on the constant in-expressions p10 in ('a', 'b') and 'a' in (p10, p11)
 * respectively, emitting joined s0.id/s1.id rows.
 *
 * Ordinals 7 and 8 (EPLOtherQueryPlan3Stream / EPLOtherQueryPlan2Stream) are
 * plan-shape-only cycles: each tryAssertion variant compiles and deploys,
 * acknowledged by a "deployed" record, then undeploys.  The 3-stream base EPL
 * ends with a trailing space so the appended ' where ...' variants carry two
 * spaces before 'where'; the 2-stream base EPL ends with a trailing space so
 * its appended 'where ...' variants carry one.
 *
 * Event types are the real common-module beans SupportBean_S0/S1/S2 and
 * SupportBean (the regression-lib beans are the same classes the suite
 * sends).  Listener rows render joined fragments row-shaped through the
 * registered-underlying protocol: a raw underlying whose class is the
 * underlying class of a registered event type renders over the engine-
 * resolved property surface, matching the InfraNamedWindowJoin oracle.
 * selectFrom collections (c1) are asserted any-order by the suite, so
 * collection values render sorted by rendered value (numbers numeric).
 */
public final class EPLOtherPlanInKeywordScenarioOracle {
    private static final String VERSION = "esper-parity/v1";
    private static final String ID = "epl-other-plan-in-keyword";
    private static final String JAVA_COMMIT = "9e1b9f1cc9117fea4bf33ab043762c045d73839c";
    private static final String JAVA_SOURCE =
            "regression-lib/src/main/java/com/espertech/esper/regressionlib/suite/epl/other/EPLOtherPlanInKeywordQuery.java";
    private static final String DESCRIPTION =
            "EPLOtherPlanInKeywordQuery ordinals 0-8: in-keyword and not-in query-plan executions over " +
            "SupportBean_S0/SupportBean_S1/SupportBean_S2. not-in (ord 0) is deploy-only. multi-idx (ord 1) " +
            "and single-idx (ord 3) replay the same send script against three surfaces each (unidirectional " +
            "join, keepall named window via on-trigger, primary-key table via on-trigger) asserting joined " +
            "s0.id/s1.id rows. multi-idx-subquery (ord 2) and single-idx-subquery (ord 4) select c0 plus a " +
            "selectFrom collection c1 (null on no match) and finish with a coercion-absence deploy-only " +
            "probe. single-idx-constants (ord 5) and multi-idx-constants (ord 6) join on constant " +
            "in-expressions. plan-3stream (ord 7) and plan-2stream (ord 8) are deploy-only plan-shape " +
            "cycles. Every observed statement carries the byte-exact INDEX_CALLBACK_HOOK @Hook annotation; " +
            "the hook class is a compile-time no-op mirror because regression-lib is not on the oracle " +
            "classpath.";

    private static final String[] CASES = {
            "not-in",
            "multi-idx-join",
            "multi-idx-window",
            "multi-idx-table",
            "multi-idx-subquery",
            "single-idx-join",
            "single-idx-window",
            "single-idx-table",
            "single-idx-subquery",
            "single-idx-constants",
            "multi-idx-constants",
            "plan-3stream",
            "plan-2stream"
    };
    private static final int[] ORDINALS = {0, 1, 1, 1, 2, 3, 3, 3, 4, 5, 6, 7, 8};
    private static final String[] RUNTIME_IDS = {
            "java-runtime-cf29d6b68db89aa0b8a8",
            "java-runtime-c982eaac78b6fd1b45ae",
            "java-runtime-c982eaac78b6fd1b45ae",
            "java-runtime-c982eaac78b6fd1b45ae",
            "java-runtime-c5daa1f63378ab985abd",
            "java-runtime-dd7da2447d43068347ff",
            "java-runtime-dd7da2447d43068347ff",
            "java-runtime-dd7da2447d43068347ff",
            "java-runtime-d1bd81d5833b3bb70b20",
            "java-runtime-b537100e9c81481cfe31",
            "java-runtime-8607ff3a12954cbb6373",
            "java-runtime-fb1e28fea28321f53bd1",
            "java-runtime-36887b719198c76fca9d"
    };
    private static final String[] EXECUTIONS = {
            "EPLOtherNotIn",
            "EPLOtherMultiIdxMultipleInAndMultirow",
            "EPLOtherMultiIdxMultipleInAndMultirow",
            "EPLOtherMultiIdxMultipleInAndMultirow",
            "EPLOtherMultiIdxSubquery",
            "EPLOtherSingleIdxMultipleInAndMultirow",
            "EPLOtherSingleIdxMultipleInAndMultirow",
            "EPLOtherSingleIdxMultipleInAndMultirow",
            "EPLOtherSingleIdxSubquery",
            "EPLOtherSingleIdxConstants",
            "EPLOtherMultiIdxConstants",
            "EPLOtherQueryPlan3Stream",
            "EPLOtherQueryPlan2Stream"
    };
    private static final String[] OBSERVATIONS = {
            "deployed; p00 not in (p10, p11) compiles and deploys with no events sent",
            "listener; unidirectional join surface of tryAssertionMultiIdx emitting joined " +
                    "s0.id/s1.id rows",
            "listener; keepall named window S1Window surface of tryAssertionMultiIdx via on " +
                    "SupportBean_S0 trigger",
            "listener; primary-key table S1Table surface of tryAssertionMultiIdx via on " +
                    "SupportBean_S0 trigger",
            "listener; c0 carries s0.id and c1 carries the selectFrom collection of matching " +
                    "s1.id or null, then a coercion-absence deploy-only probe",
            "listener; unidirectional join surface of tryAssertionSingleIdx emitting joined " +
                    "s0.id/s1.id rows",
            "listener; keepall named window S0Window surface of tryAssertionSingleIdx via on " +
                    "SupportBean_S1 trigger",
            "listener; primary-key table S0Table surface of tryAssertionSingleIdx via on " +
                    "SupportBean_S1 trigger",
            "listener; c0 carries s1.id and c1 carries the selectFrom collection of matching " +
                    "s0.id or null, then a coercion-absence deploy-only probe",
            "listener; unidirectional join on p10 in ('a', 'b') emitting joined s0.id/s1.id rows",
            "listener; unidirectional join on 'a' in (p10, p11) emitting joined s0.id/s1.id rows",
            "deployed; four compile/deploy cycles of the three-stream in-keyword join with no " +
                    "events sent",
            "deployed; thirteen compile/deploy cycles of the two-stream in-keyword join variants " +
                    "with no events sent"
    };

    private static final String[] JAVA_RUNTIMES = {
            "java-runtime-cf29d6b68db89aa0b8a8",
            "java-runtime-c982eaac78b6fd1b45ae",
            "java-runtime-c5daa1f63378ab985abd",
            "java-runtime-dd7da2447d43068347ff",
            "java-runtime-d1bd81d5833b3bb70b20",
            "java-runtime-b537100e9c81481cfe31",
            "java-runtime-8607ff3a12954cbb6373",
            "java-runtime-fb1e28fea28321f53bd1",
            "java-runtime-36887b719198c76fca9d"
    };
    private static final String[] JAVA_NAMES = {
            "EPLOtherNotIn",
            "EPLOtherMultiIdxMultipleInAndMultirow",
            "EPLOtherMultiIdxSubquery",
            "EPLOtherSingleIdxMultipleInAndMultirow",
            "EPLOtherSingleIdxSubquery",
            "EPLOtherSingleIdxConstants",
            "EPLOtherMultiIdxConstants",
            "EPLOtherQueryPlan3Stream",
            "EPLOtherQueryPlan2Stream"
    };
    private static final String[] JAVA_STATIC_IDS = {
            "java-61ef48fd70c1eb9fb712",
            "java-150700e404fe914eb1e9",
            "java-6f47e17a2b64ac117a22",
            "java-6124a7e0a85c0c5cad08",
            "java-a848701a26a2f89a8e81",
            "java-9a9e2f1ca46c53feffb0",
            "java-07fef47260a50e65bca4",
            "java-3f44a9a497b71647f01d",
            "java-2587b5e921c4bc0c5be0"
    };
    private static final String[] JAVA_FLAGS = {"INVALIDITY"};

    /**
     * Byte-exact INDEX_CALLBACK_HOOK: IndexBackingTableInfo concatenates
     * "@Hook(type=" + HookType.class.getName() + ".INTERNAL_QUERY_PLAN,hook='" +
     * SupportQueryPlanIndexHook.resetGetClassName() + "')" with NO trailing
     * space, so the hook text abuts the following select/on keyword.
     */
    private static final String HOOK =
            "@Hook(type=com.espertech.esper.common.client.annotation.HookType.INTERNAL_QUERY_PLAN," +
            "hook='com.espertech.esper.regressionlib.support.util.SupportQueryPlanIndexHook')";

    // EPLOtherNotIn (ordinal 0): HOOK + "select ..." with no separating space.
    private static final String NOT_IN_EPL = HOOK +
            "select * from SupportBean_S0 as s0 unidirectional, SupportBean_S1#keepall as s1 " +
            "where p00 not in (p10, p11)";

    // EPLOtherMultiIdxMultipleInAndMultirow (ordinal 1): "@name('s0') " + HOOK +
    // "select/on ..." (one space after the name annotation, none after the hook).
    private static final String MULTI_JOIN_EPL = "@name('s0') " + HOOK +
            "select * from SupportBean_S0 as s0 unidirectional, SupportBean_S1#keepall as s1 " +
            "where p00 in (p10, p11) and p01 in (p12, p13)";
    private static final String MULTI_WINDOW_CREATE =
            "@public create window S1Window#keepall as SupportBean_S1";
    private static final String MULTI_WINDOW_INSERT =
            "insert into S1Window select * from SupportBean_S1";
    private static final String MULTI_WINDOW_TRIGGER = "@name('s0') " + HOOK +
            "on SupportBean_S0 as s0 select * from S1Window as s1 " +
            "where p00 in (p10, p11) and p01 in (p12, p13)";
    private static final String MULTI_TABLE_CREATE =
            "@public create table S1Table(id int primary key, p10 string primary key, " +
            "p11 string primary key, p12 string primary key, p13 string primary key)";
    private static final String MULTI_TABLE_INSERT =
            "insert into S1Table select * from SupportBean_S1";
    private static final String MULTI_TABLE_TRIGGER = "@name('s0') " + HOOK +
            "on SupportBean_S0 as s0 select * from S1Table as s1 " +
            "where p00 in (p10, p11) and p01 in (p12, p13)";

    // EPLOtherMultiIdxSubquery (ordinal 2): the suite's literal concatenation
    // leaves THREE spaces between 's1' and 'where' inside the subquery.
    private static final String MULTI_SUBQUERY_EPL = "@name('s0') " + HOOK +
            "select s0.id as c0," +
            "(select * from SupportBean_S1#keepall as s1 " +
            "  where s0.p00 in (s1.p10, SupportBean_S1.p11) and s0.p01 in (s1.p12, SupportBean_S1.p13))" +
            ".selectFrom(a=>SupportBean_S1.id) as c1 " +
            "from SupportBean_S0 as s0";
    private static final String MULTI_COERCION_EPL = HOOK +
            "select *," +
            "(select * from SupportBean_S0#keepall as s0 where sb.longPrimitive in (id)) " +
            "from SupportBean as sb";

    // EPLOtherSingleIdxMultipleInAndMultirow (ordinal 3).
    private static final String SINGLE_JOIN_EPL = "@name('s0') " + HOOK +
            "select * from SupportBean_S0#keepall as s0, SupportBean_S1 as s1 unidirectional " +
            "where p00 in (p10, p11) and p01 in (p12, p13)";
    private static final String SINGLE_WINDOW_CREATE =
            "@public create window S0Window#keepall as SupportBean_S0";
    private static final String SINGLE_WINDOW_INSERT =
            "insert into S0Window select * from SupportBean_S0";
    private static final String SINGLE_WINDOW_TRIGGER = "@name('s0') " + HOOK +
            "on SupportBean_S1 as s1 select * from S0Window as s0 " +
            "where p00 in (p10, p11) and p01 in (p12, p13)";
    private static final String SINGLE_TABLE_CREATE =
            "@public create table S0Table(id int primary key, p00 string primary key, " +
            "p01 string primary key, p02 string primary key, p03 string primary key)";
    private static final String SINGLE_TABLE_INSERT =
            "insert into S0Table select * from SupportBean_S0";
    private static final String SINGLE_TABLE_TRIGGER = "@name('s0') " + HOOK +
            "on SupportBean_S1 as s1 select * from S0Table as s0 " +
            "where p00 in (p10, p11) and p01 in (p12, p13)";

    // EPLOtherSingleIdxSubquery (ordinal 4): THREE spaces between 's0' and
    // 'where' inside the subquery and TWO spaces between 'c1' and 'from'.
    private static final String SINGLE_SUBQUERY_EPL = "@name('s0') " + HOOK +
            "select s1.id as c0," +
            "(select * from SupportBean_S0#keepall as s0 " +
            "  where s0.p00 in (s1.p10, SupportBean_S1.p11) and s0.p01 in (s1.p12, SupportBean_S1.p13))" +
            ".selectFrom(a=>SupportBean_S0.id) as c1 " +
            " from SupportBean_S1 as s1";
    private static final String SINGLE_COERCION_EPL = HOOK +
            "select *," +
            "(select * from SupportBean#keepall as sb where sb.longPrimitive in (s0.id)) " +
            "from SupportBean_S0 as s0";

    private static final String SINGLE_CONSTANTS_EPL = "@name('s0') " + HOOK +
            "select * from SupportBean_S0 as s0 unidirectional, SupportBean_S1#keepall as s1 " +
            "where p10 in ('a', 'b')";
    private static final String MULTI_CONSTANTS_EPL = "@name('s0') " + HOOK +
            "select * from SupportBean_S0 as s0 unidirectional, SupportBean_S1#keepall as s1 " +
            "where 'a' in (p10, p11)";

    // EPLOtherQueryPlan3Stream (ordinal 7): tryAssertion prepends HOOK to the
    // base EPL, which itself starts "@name('s0') select ..." and ends with a
    // trailing space, so each variant has HOOK + "@name('s0') ..." and two
    // spaces before 'where'.
    private static final String PLAN3_BASE =
            "@name('s0') select * from SupportBean_S0 as s0 unidirectional, " +
            "SupportBean_S1#keepall, SupportBean_S2#keepall ";
    private static final String[] PLAN3_WHERE = {
            " where p00 in (p10, p11)",
            " where p00 in (p10, p20)",
            " where p10 in (p00, p01)",
            " where p10 in (p00, p20)"
    };

    // EPLOtherQueryPlan2Stream (ordinal 8): tryAssertion prepends HOOK to each
    // variant; the base EPL ends with a trailing space and the where-variants
    // append 'where ...' directly (one space before 'where').  The outer-join
    // variant uses its own base text.
    private static final String PLAN2_BASE =
            "select * from SupportBean_S0 as s0 unidirectional, SupportBean_S1#keepall ";
    private static final String PLAN2_OUTER_BASE =
            "select * from SupportBean_S0 as s0 unidirectional full outer join " +
            "SupportBean_S1#keepall ";
    private static final String[] PLAN2_EPLS = {
            PLAN2_BASE,
            PLAN2_BASE + "where p00 = p10",
            PLAN2_BASE + "where p00 = p10 and p00 in (p11, p12, p13)",
            PLAN2_BASE + "where p00 in (p11, p12)",
            PLAN2_BASE + "where p00 = p11 or p00 = p12",
            PLAN2_OUTER_BASE + "where p00 in (p11, p12)",
            PLAN2_BASE + "where 'A' in (p11, p12)",
            PLAN2_BASE + "where 'A' = p11 or 'A' = p12",
            PLAN2_BASE + "where 'A' in ('B', p12)",
            PLAN2_BASE + "where 'A' in ('B', 'C')",
            PLAN2_BASE + "where p10 in (p00, p01)",
            PLAN2_BASE + "where p10 in ('A', p01)",
            PLAN2_BASE + "where p10 in ('A', 'B')"
    };

    /** Deploy labels per case and deploy index, parallel to deployEpl. */
    private static String deployLabel(String caseName, int deployIndex) {
        switch (caseName) {
            case "not-in":
                return "plan";
            case "multi-idx-join":
            case "single-idx-join":
            case "single-idx-constants":
            case "multi-idx-constants":
                if (deployIndex == 0) {
                    return "s0";
                }
                break;
            case "multi-idx-subquery":
            case "single-idx-subquery":
                if (deployIndex == 0) {
                    return "s0";
                }
                if (deployIndex == 1) {
                    return "coercion";
                }
                break;
            case "plan-3stream":
                return "s0";
            case "multi-idx-window":
            case "single-idx-window":
                if (deployIndex == 0) {
                    return "create";
                }
                if (deployIndex == 1) {
                    return "insert";
                }
                if (deployIndex == 2) {
                    return "s0";
                }
                break;
            case "multi-idx-table":
                if (deployIndex == 0) {
                    return "create";
                }
                if (deployIndex == 1) {
                    return "insert";
                }
                if (deployIndex >= 2 && deployIndex <= 5) {
                    return "idx" + (deployIndex - 1);
                }
                if (deployIndex == 6) {
                    return "s0";
                }
                break;
            case "single-idx-table":
                if (deployIndex == 0) {
                    return "create";
                }
                if (deployIndex == 1) {
                    return "insert";
                }
                if (deployIndex == 2 || deployIndex == 3) {
                    return "idx" + (deployIndex - 1);
                }
                if (deployIndex == 4) {
                    return "s0";
                }
                break;
            case "plan-2stream":
                return "plan";
            default:
                throw new IllegalArgumentException("unexpected case " + caseName);
        }
        throw new IllegalArgumentException("unexpected deploy index " + deployIndex
                + " for case " + caseName);
    }

    /** Byte-exact EPL per case and deploy index. */
    private static String deployEpl(String caseName, int deployIndex) {
        switch (caseName) {
            case "not-in":
                if (deployIndex == 0) {
                    return NOT_IN_EPL;
                }
                break;
            case "multi-idx-join":
                if (deployIndex == 0) {
                    return MULTI_JOIN_EPL;
                }
                break;
            case "multi-idx-window":
                if (deployIndex == 0) {
                    return MULTI_WINDOW_CREATE;
                }
                if (deployIndex == 1) {
                    return MULTI_WINDOW_INSERT;
                }
                if (deployIndex == 2) {
                    return MULTI_WINDOW_TRIGGER;
                }
                break;
            case "multi-idx-table":
                if (deployIndex == 0) {
                    return MULTI_TABLE_CREATE;
                }
                if (deployIndex == 1) {
                    return MULTI_TABLE_INSERT;
                }
                if (deployIndex >= 2 && deployIndex <= 5) {
                    return "create index S1Idx" + (deployIndex - 1) + " on S1Table(p1"
                            + (deployIndex - 2) + ")";
                }
                if (deployIndex == 6) {
                    return MULTI_TABLE_TRIGGER;
                }
                break;
            case "multi-idx-subquery":
                if (deployIndex == 0) {
                    return MULTI_SUBQUERY_EPL;
                }
                if (deployIndex == 1) {
                    return MULTI_COERCION_EPL;
                }
                break;
            case "single-idx-join":
                if (deployIndex == 0) {
                    return SINGLE_JOIN_EPL;
                }
                break;
            case "single-idx-window":
                if (deployIndex == 0) {
                    return SINGLE_WINDOW_CREATE;
                }
                if (deployIndex == 1) {
                    return SINGLE_WINDOW_INSERT;
                }
                if (deployIndex == 2) {
                    return SINGLE_WINDOW_TRIGGER;
                }
                break;
            case "single-idx-table":
                if (deployIndex == 0) {
                    return SINGLE_TABLE_CREATE;
                }
                if (deployIndex == 1) {
                    return SINGLE_TABLE_INSERT;
                }
                if (deployIndex == 2 || deployIndex == 3) {
                    return "create index S0Idx" + (deployIndex - 1) + " on S0Table(p0"
                            + (deployIndex - 2) + ")";
                }
                if (deployIndex == 4) {
                    return SINGLE_TABLE_TRIGGER;
                }
                break;
            case "single-idx-subquery":
                if (deployIndex == 0) {
                    return SINGLE_SUBQUERY_EPL;
                }
                if (deployIndex == 1) {
                    return SINGLE_COERCION_EPL;
                }
                break;
            case "single-idx-constants":
                if (deployIndex == 0) {
                    return SINGLE_CONSTANTS_EPL;
                }
                break;
            case "multi-idx-constants":
                if (deployIndex == 0) {
                    return MULTI_CONSTANTS_EPL;
                }
                break;
            case "plan-3stream":
                if (deployIndex < PLAN3_WHERE.length) {
                    return HOOK + PLAN3_BASE + PLAN3_WHERE[deployIndex];
                }
                break;
            case "plan-2stream":
                if (deployIndex < PLAN2_EPLS.length) {
                    return HOOK + PLAN2_EPLS[deployIndex];
                }
                break;
            default:
                throw new IllegalArgumentException("unexpected case " + caseName);
        }
        throw new IllegalArgumentException("unexpected deploy index " + deployIndex
                + " for case " + caseName);
    }

    /** EPL pinned in the cases[] metadata: the observed statement per case. */
    private static String caseEpl(String caseName) {
        switch (caseName) {
            case "multi-idx-window":
                return MULTI_WINDOW_TRIGGER;
            case "multi-idx-table":
                return MULTI_TABLE_TRIGGER;
            case "single-idx-window":
                return SINGLE_WINDOW_TRIGGER;
            case "single-idx-table":
                return SINGLE_TABLE_TRIGGER;
            case "plan-3stream":
                return HOOK + PLAN3_BASE + PLAN3_WHERE[0];
            case "plan-2stream":
                return HOOK + PLAN2_EPLS[0];
            default:
                return deployEpl(caseName, 0);
        }
    }

    private EPLOtherPlanInKeywordScenarioOracle() {
    }

    public static void main(String[] args) throws Exception {
        if (args.length != 1) {
            throw new IllegalArgumentException(
                    "usage: EPLOtherPlanInKeywordScenarioOracle <scenario.json>");
        }
        JsonValue parsed = Json.parse(Files.readString(Path.of(args[0]), StandardCharsets.UTF_8));
        if (!parsed.isObject()) {
            throw new IllegalArgumentException("scenario must be a JSON object");
        }
        rejectDuplicateKeys(parsed);
        JsonObject scenario = parsed.asObject();
        validateScenario(scenario);

        JsonArray records = new JsonArray();
        JsonArray steps = scenario.get("steps").asArray();
        for (int index = 0; index < CASES.length; index++) {
            runCase(steps, CASES[index], RUNTIME_IDS[index], index, records);
        }

        System.out.println(new JsonObject().add("version", VERSION).add("id", ID)
                .add("javaCommit", JAVA_COMMIT).add("java", System.getProperty("java.version"))
                .add("records", records));
    }

    private static void runCase(JsonArray steps, String caseName, String runtimeId,
                                int caseIndex, JsonArray records) throws Exception {
        Configuration configuration = new Configuration();
        configuration.getRuntime().getThreading().setInternalTimerEnabled(false);
        configuration.getCommon().addEventType("SupportBean", SupportBean.class);
        configuration.getCommon().addEventType("SupportBean_S0", SupportBean_S0.class);
        configuration.getCommon().addEventType("SupportBean_S1", SupportBean_S1.class);
        configuration.getCommon().addEventType("SupportBean_S2", SupportBean_S2.class);

        String runtimeURI = "parity-" + ID + "-" + runtimeId;
        EPRuntime runtime = EPRuntimeProvider.getRuntime(runtimeURI, configuration);
        ((EPRuntimeSPI) runtime).initialize(0L);
        try {
            // Registered-underlying protocol support (see class Javadoc):
            // underlying classes of preconfigured bean event types mapped to
            // their engine-resolved event types.
            Map<Class<?>, EventType> underlyingEventTypes = new HashMap<>();
            for (String typeName : new String[]{
                    "SupportBean", "SupportBean_S0", "SupportBean_S1", "SupportBean_S2"}) {
                EventType eventType =
                        runtime.getEventTypeService().getEventTypePreconfigured(typeName);
                if (eventType != null) {
                    underlyingEventTypes.put(eventType.getUnderlyingType(), eventType);
                }
            }
            long[] sequence = {0};
            TraceWriter writer = new TraceWriter(records, caseName, runtime, sequence,
                    underlyingEventTypes);
            Map<String, EPStatement> statements = new HashMap<>();
            boolean active = false;
            int deployIndex = 0;
            for (int index = 0; index < steps.size(); index++) {
                JsonObject step = steps.get(index).asObject();
                String operation = step.getString("op", "");
                if ("case".equals(operation)) {
                    active = caseName.equals(step.getString("case", ""));
                    continue;
                }
                if (!active) {
                    continue;
                }
                switch (operation) {
                    case "deploy": {
                        String label = step.getString("statement", "");
                        String epl = deployEpl(caseName, deployIndex);
                        if (!label.equals(deployLabel(caseName, deployIndex))
                                || !epl.equals(step.getString("epl", ""))) {
                            throw new IllegalArgumentException("deploy is not pinned for case "
                                    + caseName + " phase " + deployIndex);
                        }
                        deployIndex++;
                        CompilerArguments arguments =
                                new CompilerArguments(runtime.getRuntimePath());
                        EPCompiled compiled =
                                EPCompilerProvider.getCompiler().compile(epl, arguments);
                        EPDeployment deployment = runtime.getDeploymentService().deploy(compiled,
                                new DeploymentOptions().setDeploymentId(
                                        ID + "-" + caseIndex + "-" + deployIndex));
                        EPStatement[] deployed = deployment.getStatements();
                        if (deployed.length != 1) {
                            throw new IllegalStateException("deployment has " + deployed.length
                                    + " statements, want 1");
                        }
                        EPStatement statement = deployed[0];
                        if ("s0".equals(label)) {
                            if (!"s0".equals(statement.getName())) {
                                throw new IllegalStateException(
                                        "statement name " + statement.getName() + ", want s0");
                            }
                            statement.addListener(writer);
                        }
                        statements.put(label, statement);
                        break;
                    }
                    case "undeploy-all":
                        runtime.getDeploymentService().undeployAll();
                        statements.clear();
                        break;
                    case "send":
                        sendEvent(runtime, step);
                        break;
                    case "deployed": {
                        String label = step.getString("statement", "");
                        if (!statements.containsKey(label)) {
                            throw new IllegalStateException(
                                    "deployed marker for unknown statement " + label);
                        }
                        records.add(new JsonObject()
                                .add("case", caseName)
                                .add("operation", "deployed")
                                .add("statement", label)
                                .add("sequence", ++sequence[0])
                                .add("time", Instant.ofEpochMilli(
                                        runtime.getEventService().getCurrentTime()).toString()));
                        break;
                    }
                    default:
                        throw new IllegalArgumentException("unsupported step op " + operation);
                }
            }
        } finally {
            runtime.getDeploymentService().undeployAll();
            runtime.destroy();
        }
    }

    private static void sendEvent(EPRuntime runtime, JsonObject step) {
        String eventType = step.getString("eventType", "");
        JsonObject payload = step.get("payload").asObject();
        switch (eventType) {
            case "SupportBean_S0": {
                SupportBean_S0 bean = new SupportBean_S0(payload.getInt("id", 0));
                if (payload.get("p00") != null) {
                    bean.setP00(payload.getString("p00", null));
                }
                if (payload.get("p01") != null) {
                    bean.setP01(payload.getString("p01", null));
                }
                if (payload.get("p02") != null) {
                    bean.setP02(payload.getString("p02", null));
                }
                if (payload.get("p03") != null) {
                    bean.setP03(payload.getString("p03", null));
                }
                runtime.getEventService().sendEventBean(bean, eventType);
                break;
            }
            case "SupportBean_S1": {
                SupportBean_S1 bean = new SupportBean_S1(payload.getInt("id", 0));
                if (payload.get("p10") != null) {
                    bean.setP10(payload.getString("p10", null));
                }
                if (payload.get("p11") != null) {
                    bean.setP11(payload.getString("p11", null));
                }
                if (payload.get("p12") != null) {
                    bean.setP12(payload.getString("p12", null));
                }
                if (payload.get("p13") != null) {
                    bean.setP13(payload.getString("p13", null));
                }
                runtime.getEventService().sendEventBean(bean, eventType);
                break;
            }
            default:
                throw new IllegalArgumentException("unsupported event type: " + eventType);
        }
    }

    private static void validateScenario(JsonObject scenario) {
        requireFields(scenario, "version", "id", "description", "javaCommit", "javaSource",
                "javaRuntimes", "javaNames", "javaStaticIds", "javaFlags",
                "cases", "steps");
        if (!VERSION.equals(string(scenario, "version"))
                || !ID.equals(string(scenario, "id"))
                || !DESCRIPTION.equals(string(scenario, "description"))
                || !JAVA_COMMIT.equals(string(scenario, "javaCommit"))
                || !JAVA_SOURCE.equals(string(scenario, "javaSource"))) {
            throw new IllegalArgumentException("scenario metadata is not pinned");
        }
        validateStringArray(scenario.get("javaRuntimes"), JAVA_RUNTIMES, "javaRuntimes");
        validateStringArray(scenario.get("javaNames"), JAVA_NAMES, "javaNames");
        validateStringArray(scenario.get("javaStaticIds"), JAVA_STATIC_IDS, "javaStaticIds");
        validateStringArray(scenario.get("javaFlags"), JAVA_FLAGS, "javaFlags");

        JsonArray cases = array(scenario.get("cases"), "cases");
        if (cases.size() != CASES.length) {
            throw new IllegalArgumentException("scenario must contain exactly "
                    + CASES.length + " cases");
        }
        for (int index = 0; index < CASES.length; index++) {
            JsonObject definition = object(cases.get(index), "case definition " + index);
            requireFields(definition, "case", "ordinal", "runtimeId", "executionName",
                    "observation", "epl");
            if (!CASES[index].equals(string(definition, "case"))
                    || integer(definition, "ordinal") != ORDINALS[index]
                    || !RUNTIME_IDS[index].equals(string(definition, "runtimeId"))
                    || !EXECUTIONS[index].equals(string(definition, "executionName"))
                    || !OBSERVATIONS[index].equals(string(definition, "observation"))
                    || !caseEpl(CASES[index]).equals(string(definition, "epl"))) {
                throw new IllegalArgumentException("case " + index + " metadata is not pinned");
            }
        }
    }

    private static void rejectDuplicateKeys(JsonValue value) {
        if (value.isObject()) {
            Set<String> names = new HashSet<>();
            for (com.espertech.esper.common.client.json.minimaljson.Member member : value.asObject()) {
                if (!names.add(member.getName())) {
                    throw new IllegalArgumentException("duplicate JSON object key: " + member.getName());
                }
                rejectDuplicateKeys(member.getValue());
            }
        } else if (value.isArray()) {
            for (JsonValue item : value.asArray()) {
                rejectDuplicateKeys(item);
            }
        }
    }

    private static void requireFields(JsonObject object, String... expectedNames) {
        if (object == null || object.size() != expectedNames.length
                || !new HashSet<>(object.names()).equals(new HashSet<>(Arrays.asList(expectedNames)))) {
            throw new IllegalArgumentException("JSON object has unexpected fields");
        }
    }

    private static String string(JsonObject object, String name) {
        JsonValue value = object.get(name);
        if (value == null || !value.isString()) {
            throw new IllegalArgumentException(name + " must be a JSON string");
        }
        return value.asString();
    }

    private static int integer(JsonObject object, String name) {
        long value = longNumber(object, name);
        if (value < Integer.MIN_VALUE || value > Integer.MAX_VALUE) {
            throw new IllegalArgumentException(name + " must be an integer JSON number");
        }
        return (int) value;
    }

    private static long longNumber(JsonObject object, String name) {
        JsonValue value = object.get(name);
        if (!(value instanceof JsonNumber)) {
            throw new IllegalArgumentException(name + " must be an integer JSON number");
        }
        String text = value.toString();
        if (!text.matches("-?(0|[1-9][0-9]*)")) {
            throw new IllegalArgumentException(name + " must be an integer JSON number");
        }
        try {
            return Long.parseLong(text, 10);
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException(name + " is outside the Java long range", ex);
        }
    }

    private static void validateStringArray(JsonValue value, String[] expected, String name) {
        JsonArray actual = array(value, name);
        if (actual.size() != expected.length) {
            throw new IllegalArgumentException(name + " length is not pinned");
        }
        for (int index = 0; index < expected.length; index++) {
            JsonValue item = actual.get(index);
            if (item == null || !item.isString() || !expected[index].equals(item.asString())) {
                throw new IllegalArgumentException(name + " mismatch at index " + index);
            }
        }
    }

    private static JsonArray array(JsonValue value, String label) {
        if (value == null || !value.isArray()) {
            throw new IllegalArgumentException(label + " must be a JSON array");
        }
        return value.asArray();
    }

    private static JsonObject object(JsonValue value, String label) {
        if (value == null || !value.isObject()) {
            throw new IllegalArgumentException(label + " must be a JSON object");
        }
        return value.asObject();
    }

    private static final class TraceWriter implements UpdateListener {
        private final JsonArray records;
        private final String caseName;
        private final EPRuntime runtime;
        private final long[] sequence;
        private final Map<Class<?>, EventType> underlyingEventTypes;

        private TraceWriter(JsonArray records, String caseName, EPRuntime runtime,
                            long[] sequence, Map<Class<?>, EventType> underlyingEventTypes) {
            this.records = records;
            this.caseName = caseName;
            this.runtime = runtime;
            this.sequence = sequence;
            this.underlyingEventTypes = underlyingEventTypes;
        }

        @Override
        public void update(EventBean[] newEvents, EventBean[] oldEvents, EPStatement statement,
                           EPRuntime ignoredRuntime) {
            if (newEvents == null && oldEvents == null) {
                return;
            }
            JsonObject record = new JsonObject()
                    .add("case", caseName)
                    .add("operation", "listener")
                    .add("statement", statement.getName())
                    .add("sequence", ++sequence[0])
                    .add("time", Instant.ofEpochMilli(runtime.getEventService().getCurrentTime()).toString());
            JsonArray newRows = rowsOf(newEvents);
            if (newRows.size() > 0) {
                record.add("new", newRows);
            }
            if (oldEvents != null && oldEvents.length > 0) {
                record.add("old", rowsOf(oldEvents));
            }
            records.add(record);
        }

        private JsonArray rowsOf(EventBean[] events) {
            JsonArray output = new JsonArray();
            if (events == null) {
                return output;
            }
            for (EventBean event : events) {
                output.add(renderRow(event));
            }
            return output;
        }

        private JsonObject renderRow(EventBean event) {
            JsonObject fields = new JsonObject();
            for (String name : new TreeSet<>(Arrays.asList(event.getEventType().getPropertyNames()))) {
                fields.add(name, normalize(event.get(name)));
            }
            return new JsonObject().add("kind", "row").add("fields", fields);
        }

        private JsonValue normalize(Object value) {
            if (value == null) {
                return new JsonObject().add("state", "null");
            }
            if (value instanceof Integer || value instanceof Long || value instanceof Short
                    || value instanceof Byte) {
                return Json.value(((Number) value).longValue());
            }
            if (value instanceof Number) {
                return Json.value(((Number) value).doubleValue());
            }
            if (value instanceof Boolean) {
                return Json.value((Boolean) value);
            }
            if (value instanceof Map<?, ?>) {
                Map<?, ?> mapValue = (Map<?, ?>) value;
                TreeSet<String> keys = new TreeSet<>();
                for (Object key : mapValue.keySet()) {
                    keys.add(String.valueOf(key));
                }
                JsonObject fields = new JsonObject();
                for (String key : keys) {
                    fields.add(key, normalize(mapValue.get(key)));
                }
                return new JsonObject().add("kind", "row").add("fields", fields);
            }
            if (value instanceof EventBean) {
                EventBean inner = (EventBean) value;
                JsonObject fields = new JsonObject();
                for (String prop : new TreeSet<>(Arrays.asList(inner.getEventType().getPropertyNames()))) {
                    fields.add(prop, normalize(inner.get(prop)));
                }
                return new JsonObject().add("kind", "row").add("fields", fields);
            }
            // Registered-underlying protocol: a raw underlying whose class is
            // the underlying class of a registered event type renders
            // row-shaped exactly like the EventBean branch instead of the
            // String.valueOf fallback (see class Javadoc).
            if (underlyingEventTypes.containsKey(value.getClass())) {
                return renderRow(new UnderlyingEventBean(value,
                        underlyingEventTypes.get(value.getClass())));
            }
            if (value instanceof Object[]) {
                JsonArray array = new JsonArray();
                for (Object item : (Object[]) value) {
                    array.add(normalize(item));
                }
                return array;
            }
            if (value instanceof Collection<?>) {
                // selectFrom collections are asserted any-order by the suite;
                // canonicalize by sorting rendered values (numbers numeric).
                List<JsonValue> rendered = new ArrayList<>();
                for (Object item : (Collection<?>) value) {
                    rendered.add(normalize(item));
                }
                rendered.sort(TraceWriter::compareJsonValues);
                JsonArray array = new JsonArray();
                for (JsonValue item : rendered) {
                    array.add(item);
                }
                return array;
            }
            return Json.value(String.valueOf(value));
        }

        private static int compareJsonValues(JsonValue left, JsonValue right) {
            if (left.isNumber() && right.isNumber()) {
                return Double.compare(left.asDouble(), right.asDouble());
            }
            return left.toString().compareTo(right.toString());
        }

        /** Minimal engine-independent EventBean view over a raw underlying. */
        private static final class UnderlyingEventBean implements EventBean {
            private final Object underlying;
            private final EventType eventType;

            UnderlyingEventBean(Object underlying, EventType eventType) {
                this.underlying = underlying;
                this.eventType = eventType;
            }

            public EventType getEventType() {
                return eventType;
            }

            public Object get(String propertyExpression) {
                return eventType.getGetter(propertyExpression).get(this);
            }

            public Object getUnderlying() {
                return underlying;
            }

            public Object getFragment(String propertyExpression) {
                return eventType.getGetter(propertyExpression).getFragment(this);
            }
        }
    }
}
