// Command genfacade generates the public esper facade from internal/esper.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const engineImport = "github.com/liubaicai/esper/internal/esper"

var allowedVariables = map[string]struct{}{
	"MathContextDECIMAL32": {},
	// Interval computers are stateless function values used as expression
	// builders (dt interval algebra); exposing the value is the facade
	// contract.
	"Before":       {},
	"After":        {},
	"Coincides":    {},
	"During":       {},
	"Includes":     {},
	"Finishes":     {},
	"FinishedBy":   {},
	"Meets":        {},
	"MetBy":        {},
	"Overlaps":     {},
	"OverlappedBy": {},
	"Starts":       {},
	"StartedBy":    {},
}

type symbol struct {
	name     string
	doc      string
	kind     token.Token
	typeSpec *ast.TypeSpec
	funcDecl *ast.FuncDecl
	fset     *token.FileSet
	imports  map[string]string
}

func main() {
	source := flag.String("source", "internal/esper", "engine package directory")
	out := flag.String("out", "facade_generated.go", "facade output file")
	flag.Parse()
	if err := generate(*source, *out); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(source, out string) error {
	entries, err := os.ReadDir(source)
	if err != nil {
		return err
	}
	symbols := make(map[string]symbol)
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		if err := collectFile(filepath.Join(source, entry.Name()), symbols); err != nil {
			return err
		}
	}

	names := make([]string, 0, len(symbols))
	for name := range symbols {
		names = append(names, name)
	}
	sort.Strings(names)
	usedImports := map[string]string{"internalengine": engineImport}
	var declarations bytes.Buffer
	for _, name := range names {
		current := symbols[name]
		switch {
		case current.typeSpec != nil:
			writeType(&declarations, current, usedImports)
		case current.funcDecl != nil:
			if err := writeFunction(&declarations, current, usedImports); err != nil {
				return err
			}
		default:
			writeDoc(&declarations, current.doc)
			declarations.WriteString(current.kind.String() + " " + current.name + " = internalengine." + current.name + "\n\n")
		}
	}

	var output bytes.Buffer
	output.WriteString("// Code generated by internal/cmd/genfacade; DO NOT EDIT.\n\npackage esper\n\n")
	writeImports(&output, usedImports)
	output.Write(declarations.Bytes())
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return fmt.Errorf("format %s: %w\n%s", out, err, output.String())
	}
	return os.WriteFile(out, formatted, 0o644)
}

func collectFile(path string, symbols map[string]symbol) error {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return err
	}
	imports := importMap(file)
	for _, declaration := range file.Decls {
		switch current := declaration.(type) {
		case *ast.GenDecl:
			for _, specification := range current.Specs {
				switch item := specification.(type) {
				case *ast.TypeSpec:
					if item.Name.IsExported() {
						addSymbol(symbols, symbol{name: item.Name.Name, doc: docText(current.Doc, item.Doc), kind: token.TYPE, typeSpec: item, fset: fset, imports: imports})
					}
				case *ast.ValueSpec:
					for _, name := range item.Names {
						if name.IsExported() {
							if current.Tok == token.VAR {
								if _, allowed := allowedVariables[name.Name]; !allowed {
									return fmt.Errorf("%s: exported variable %s requires facade semantics review", path, name.Name)
								}
							}
							addSymbol(symbols, symbol{name: name.Name, doc: docText(current.Doc, item.Doc), kind: current.Tok, fset: fset, imports: imports})
						}
					}
				}
			}
		case *ast.FuncDecl:
			if current.Recv == nil && current.Name.IsExported() {
				addSymbol(symbols, symbol{name: current.Name.Name, doc: docText(current.Doc), kind: token.FUNC, funcDecl: current, fset: fset, imports: imports})
			}
		}
	}
	return nil
}

func addSymbol(symbols map[string]symbol, candidate symbol) {
	if _, exists := symbols[candidate.name]; !exists {
		symbols[candidate.name] = candidate
	}
}

func writeType(out *bytes.Buffer, current symbol, used map[string]string) {
	writeDoc(out, current.doc)
	out.WriteString("type " + current.name)
	typeParameters := current.typeSpec.TypeParams
	if typeParameters != nil {
		out.WriteString(typeParameterString(current.fset, typeParameters))
		collectImports(typeParameters, current.imports, used)
	}
	out.WriteString(" = internalengine." + current.name)
	writeTypeArguments(out, typeParameters)
	out.WriteString("\n\n")
}

func writeFunction(out *bytes.Buffer, current symbol, used map[string]string) error {
	function := current.funcDecl
	if err := ensureNamedParameters(function.Type.Params); err != nil {
		return fmt.Errorf("public function %s: %w", current.name, err)
	}
	writeDoc(out, current.doc)
	out.WriteString("func " + current.name)
	signature := nodeString(current.fset, function.Type)
	out.WriteString(strings.TrimPrefix(signature, "func"))
	if function.Type.TypeParams != nil {
		collectImports(function.Type.TypeParams, current.imports, used)
	}
	collectImports(function.Type.Params, current.imports, used)
	if function.Type.Results != nil {
		collectImports(function.Type.Results, current.imports, used)
	}
	out.WriteString(" {\n")
	if function.Type.Results != nil && len(function.Type.Results.List) > 0 {
		out.WriteString("return ")
	}
	out.WriteString("internalengine." + current.name)
	writeTypeArguments(out, function.Type.TypeParams)
	out.WriteByte('(')
	first := true
	for _, field := range function.Type.Params.List {
		for _, name := range field.Names {
			if !first {
				out.WriteString(", ")
			}
			first = false
			out.WriteString(name.Name)
			if _, variadic := field.Type.(*ast.Ellipsis); variadic {
				out.WriteString("...")
			}
		}
	}
	out.WriteString(")\n}\n\n")
	return nil
}

func writeTypeArguments(out *bytes.Buffer, parameters *ast.FieldList) {
	if parameters == nil {
		return
	}
	out.WriteByte('[')
	first := true
	for _, field := range parameters.List {
		for _, name := range field.Names {
			if !first {
				out.WriteString(", ")
			}
			first = false
			out.WriteString(name.Name)
		}
	}
	out.WriteByte(']')
}

func ensureNamedParameters(parameters *ast.FieldList) error {
	if parameters == nil {
		return nil
	}
	for _, field := range parameters.List {
		if len(field.Names) == 0 {
			return fmt.Errorf("unnamed parameters are not supported")
		}
	}
	return nil
}

func docText(groups ...*ast.CommentGroup) string {
	var out strings.Builder
	for _, group := range groups {
		if group == nil {
			continue
		}
		for _, comment := range group.List {
			out.WriteString(comment.Text)
			out.WriteByte('\n')
		}
	}
	return out.String()
}

func writeDoc(out *bytes.Buffer, doc string) {
	out.WriteString(doc)
}

func importMap(file *ast.File) map[string]string {
	result := make(map[string]string)
	for _, specification := range file.Imports {
		path, _ := strconv.Unquote(specification.Path.Value)
		name := filepath.Base(path)
		if specification.Name != nil {
			name = specification.Name.Name
		}
		result[name] = path
	}
	return result
}

func collectImports(node ast.Node, available, used map[string]string) {
	if node == nil {
		return
	}
	ast.Inspect(node, func(current ast.Node) bool {
		selector, ok := current.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		identifier, ok := selector.X.(*ast.Ident)
		if !ok {
			return true
		}
		if path, ok := available[identifier.Name]; ok {
			used[identifier.Name] = path
		}
		return true
	})
}

func writeImports(out *bytes.Buffer, imports map[string]string) {
	names := make([]string, 0, len(imports))
	for name := range imports {
		names = append(names, name)
	}
	sort.Strings(names)
	out.WriteString("import (\n")
	for _, name := range names {
		path := imports[name]
		if name == "internalengine" {
			fmt.Fprintf(out, "\tinternalengine %q\n", path)
		} else if name == filepath.Base(path) {
			fmt.Fprintf(out, "\t%q\n", path)
		} else {
			fmt.Fprintf(out, "\t%s %q\n", name, path)
		}
	}
	out.WriteString(")\n\n")
}

func nodeString(fset *token.FileSet, node any) string {
	var buffer bytes.Buffer
	_ = format.Node(&buffer, fset, node)
	return buffer.String()
}

func typeParameterString(fset *token.FileSet, parameters *ast.FieldList) string {
	function := &ast.FuncType{Func: token.NoPos, TypeParams: parameters, Params: &ast.FieldList{}}
	signature := nodeString(fset, function)
	signature = strings.TrimPrefix(signature, "func")
	return strings.TrimSuffix(signature, "()")
}
